WebsitesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: WebsitesTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: status
        AttributeType: S
      - AttributeName: siteName
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: statusAndSiteName
        KeySchema:
          - AttributeName: status
            KeyType: HASH
          - AttributeName: siteName
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
